### ISSUE TITLE
TypeError: Cannot assign bool to property GrahamCampbell\Throttle\Throttler\CacheThrottler::$number of type ?int

### ISSUE THREAD

**Issue by jonhassall** [GrahamCampbell/Laravel-Throttle#103]
I frequently get this error:

`TypeError: Cannot assign bool to property GrahamCampbell\Throttle\Throttler\CacheThrottler::$number of type ?int
`

For me, this often happens when calling `$throttler->clear();`. Should there be error detection or casting to int in [hitRedis](https://github.com/GrahamCampbell/Laravel-Throttle/blob/10.0/src/Throttler/CacheThrottler.php)?

```
    /**
     * An atomic hit implementation for redis.
     *
     * @return void
     */
    private function hitRedis(): void
    {
        $lua = 'local v = redis.call(\'incr\', KEYS[1]) '.
               'if v>1 then return v '.
               'else redis.call(\'setex\', KEYS[1], ARGV[1], 1) return 1 end';

        $this->number = $this->store->connection()->eval($lua, 1, $this->computeRedisKey(), $this->time);
    }
```

**Comment by GrahamCampbell** [comment]
Thanks for the report. This is fixed in v10.1.0.
