### ISSUE TITLE
Time has no effect

### ISSUE THREAD

**Issue by mor619dx** [GrahamCampbell/Laravel-Throttle#11]
EDIT:
Apparently the time is in minutes and not in seconds, my bad.
Also I noticed shared hosting servers don't support redis or memcached,
I use fcache to overcome the tags missing problem in the file driver but is there another better solution?

Hi,
I'm trying to use this package in simple way like:
            $data = array('ip' => '127.0.0.1', 'route' => 'http://laravel.com/');
            $throttler = Throttle::get($data, 10, 60);

```
        echo "did we pass the limit?:";
        echo var_dump($throttler->check());

        echo "attempt";
        echo var_dump($throttler->attempt());

        echo "count:";
        echo var_dump(count($throttler));
```

I see that time has no effect, when I pass the 10 time and I wait 60 seconds (is it in seconds right?)
the attempt and check still return false although they should have returned true since the time has passed.

I couldn't find share hosting that support redis or memcached so I use Fcache driver since it support  tags function.

https://github.com/artdevue/Fcache

I tried to debug it myself but I couldn't find anything related to time in this package, is it assume cached delete after the time ?

thank for your help,
Mor.

**Comment by juanvillegas** [comment]
Suppose I want to use seconds, would it make sense to use 0.5 to represent 30 seconds? 0.25 to represent 15 seconds? and so on?

**Comment by jbrooksuk** [comment]
Yes.

**Comment by GrahamCampbell** [comment]
No. The phpdoc says you must only pass an integer. The fact other values may work is merely a happy coincidence, and was not intended by design.
