### ISSUE TITLE
does not have a method 'tags'

### ISSUE THREAD

**Issue by sirsquall** [GrahamCampbell/Laravel-Throttle#13]
Hi, 
I'm using the Laravel Framework version 4.2.11.

And I have this error message : 

``` php
call_user_func_array() expects parameter 1 to be a valid callback, class 'Illuminate\Cache\DatabaseStore' does not have a method 'tags'
```

I have switched to file but I have the same :

``` php
call_user_func_array() expects parameter 1 to be a valid callback, class 'Illuminate\Cache\FileStore' does not have a method 'tags'
```

Any idea ?

**Comment by rafis** [comment]
It easy to implement tags in both file and database cache drivers, but dont know why Laravel authors doesn't do it.

**Comment by GrahamCampbell** [comment]
I doubt laravel will ever support cache tags on database/file drivers.

**Comment by GrahamCampbell** [comment]
I've decided to remove the need for tags. This will arrive in the 4.0 release. See #26.
