### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by amilajack** [GrahamCampbell/Laravel-Throttle#18]
I just setup Laravel Throttle and in my home.blade.php, I have the following:
```
<?php
$request = Request::getFacadeRoot();
  $throttler = Throttle::get($request, 50, 30);
  var_dump($throttler->check());
  var_dump($throttler->count());
?>
```
and I get the following on each rendering of the view:
```
boolean true
int 0
```
Where should I include the code in order to make it work properly?

**Comment by GrahamCampbell** [comment]
Yeh, that's the expected behaviour. check tells you if the user hasn't bust the limit, and count tells you how many "hits" you've had.

**Comment by GrahamCampbell** [comment]
https://github.com/GrahamCampbell/Laravel-Throttle/blob/master/tests/ThrottleTest.php
