### ISSUE TITLE
Throttle::attempt() goes over limit before returning "false"

### ISSUE THREAD

**Issue by dcro** [GrahamCampbell/Laravel-Throttle#19]
With the following code:

```php
if (!Throttle::attempt($request, 5)) {
    throw new Exception('Over limit');
}

doSomething();
```

The exception is not thrown on the sixth attempt as expected, but on the seventh. The issue seems related to issue #6.

**Comment by GrahamCampbell** [comment]
What version are you using?

**Comment by dcro** [comment]
Sorry, forgot to mention. I'm using version 3.0.

**Comment by GrahamCampbell** [comment]
How come these tests are passing then?

https://github.com/GrahamCampbell/Laravel-Throttle/blob/master/tests/Functional/FilterTest.php

**Comment by dcro** [comment]
The `hit()` method in those tests is also broken. If you call `hit(10)`, it actually calls `GET throttle-test-route` 11 times: 10 times in the `for (...)` loop and once more after that in the `try {...} catch {}` block.

The correct test would be:

```php
        for ($i = 0; $i < $times - 1; $i++) {
            $this->call('GET', 'throttle-test-route');
            $this->assertResponseOk();
        }
```
since you're starting with 0 (`$i = 0`).

**Comment by GrahamCampbell** [comment]
Wait, so I updated 2.0 based on someone's request, and actually broke it because it was working fine the first time.

NB, not `$times - 1` though. I'll just use =< rather than </

**Comment by GrahamCampbell** [comment]
Could you send a fix to the master please, and update the branch alias to 3.1-dev as you do. :)

**Comment by dcro** [comment]
I'll try to put together a pull request for this next week.

**Comment by GrahamCampbell** [comment]
Thanks.

**Comment by lazychaser** [comment]
Experiencing same issue, where's the patch? :-)

**Comment by GrahamCampbell** [comment]
There isn't one. I'm open to someone writing one though. I would have done by, now, but I'm totally snowed under atm, so don't have any time atm.

**Comment by lazychaser** [comment]
@GrahamCampbell please accept pull request
