### ISSUE TITLE
Using this for Auth attempts

### ISSUE THREAD

**Issue by alnutile** [GrahamCampbell/Laravel-Throttle#20]
Just wondering if I am not using the right tool for the job. I want to block a user who does a post to auth/login x number of times.

I do have all of that working but with that comes the need, as an admin of the site, to also clear a users blocked state instead of making them wait to try again in x number of minutes.

If this is the right tool for that job then how would I go about allowing an admin user to clear this blocked state? For example an artisan command like

~~~
php artisan throttle:clear 10.0.2.2 /auth/login
~~~

Was one thing I was trying but had trouble getting it to clear. 

~~~
    public function fire()
    {
        $this->setIp($this->argument('ip'));
        $this->setRoutUri($this->argument('route_uri'));


        $request = ['ip' => $this->getIp(), 'route' => $this->getRoutUri()];
        Throttle::clear($request);

        $this->info(sprintf("Blocked state cleared for IP %s and route %s", $this->getIp(), $this->getRoutUri()));
    }
~~~

thanks!

**Comment by GrahamCampbell** [comment]
Which version are you using?

**Comment by alnutile** [comment]
Sorry about that.
We are going to use both (running a number of L4 sites but now going L5 with new sites) this example is L4 so the 2.0 branch

**Comment by GrahamCampbell** [comment]
Ok, yeh. This will only work as you're expecting it to work, on the L5 version. This is due to this change: https://github.com/GrahamCampbell/Laravel-Throttle/commit/43af3a945c0825a82b9727ff7690aab9e9f12fbf. It was technically breaking, so I didn't do it on the 2.0 branch.

**Comment by GrahamCampbell** [comment]
What this means is you need to provide the identical "time" and "limit" to flush caches in 2.0, but you don't in 3.0.

**Comment by alnutile** [comment]
okay, thanks. btw do you think this is a good use of the tool? It seems to be more about rate limiting.

**Comment by GrahamCampbell** [comment]
Yeh, this usage case looks fine.
