### ISSUE TITLE
Any validation on ip address

### ISSUE THREAD

**Issue by nlassiter** [GrahamCampbell/Laravel-Throttle#21]
First, thanks for your work on this project.

I have a question. I'm using this package to implement rate limits for an api. The rate limits are per account, as opposed to being per IP address. Because of that, I'm using a format like this:
```php
Throttle::get(['ip' => 222, 'route' => 'account.event.minute']);
```
Where 222 is an account ID. This seems to work fine. I didn't see where the 'ip' value was going through any validation, so I don't see why it wouldn't work, but you mentioned that 'route' could be set to different values for advanced usage, but didn't mention setting the 'ip' index to different values, so I thought I'd check to see if you knew of any potential problems with this.

Originally, I had the account ID within the 'route' value and was just using a constant IP, but changed to the format above so that I could easily reset counters with
```php
Cache::tags('throttle', '222')->flush()
```

Thanks again

**Comment by GrahamCampbell** [comment]
There is no validation on that field value, though I'm not quite sure what your question is. Also, what version of this package are you using?

**Comment by nlassiter** [comment]
I'm using the latest version: "graham-campbell/throttle": "~3.0"
Basically I just wanted to confirm there was no validation on the field and no other consequences for using some other identifier (such as a resource ID) in place of an IP address.

**Comment by GrahamCampbell** [comment]
Yeh, that should be totally fine. I might even rename "ip" to "id" or "user", or something in 4.x.

**Comment by nlassiter** [comment]
Since it's saved as a tag in cache, you might consider naming it "tag_id"

**Comment by nlassiter** [comment]
Thanks again

**Comment by GrahamCampbell** [comment]
> Since it's saved as a tag in cache, you might consider naming it "tag_id"

It's not actually the cache id though. We calculate that another way. See https://github.com/GrahamCampbell/Laravel-Throttle/blob/master/src/Data.php#L142.
