### ISSUE TITLE
any plan for lumen ?

### ISSUE THREAD

**Issue by devmark** [GrahamCampbell/Laravel-Throttle#23]

**Comment by GrahamCampbell** [comment]
Should work with Lumen.

**Comment by GrahamCampbell** [comment]
I don't intend to add docs for that usage though. Anyone using Lumen should be able to get it going on their own.

**Comment by GrahamCampbell** [comment]
@devmark Lumen will be supported from 4.1 and newer. :)

**Comment by devmark** [comment]
nice, thanks you :+1:
