### ISSUE TITLE
Can I use this for my UseCase?

### ISSUE THREAD

**Issue by ChristianGiupponi** [GrahamCampbell/Laravel-Throttle#24]
I have multiple users on my application and each of them have a role.

If user has the role "1" he can access to a uri for 1000times
If user has role "2" he can accesso 2000times
and so on

With this package I can set the limit for each user?  I dind't find any docs about this.

Thanks!

**Comment by GrahamCampbell** [comment]
This is a middleware you'd be implementing yourself, using my code.
