### ISSUE TITLE
Wrong version number in readme.md

### ISSUE THREAD

**Issue by icedfish** [GrahamCampbell/Laravel-Throttle#25]
the line:  

	"graham-campbell/throttle": "~4.0"

should be 

	"graham-campbell/throttle": "~3.0"

Otherwise the composer will report error:

	Your requirements could not be resolved to an installable set of packages.

	  Problem 1
	    - The requested package graham-campbell/throttle could not be found in any version, there may be a typo in the package name.

**Comment by icedfish** [comment]
2 more typo in readme.md:

	// let's check if we've gone over the limit
	var_dump($thottler->check());

	// we implement Countable
	var_dump(count($thottler));
	
the two **$thottler** should be **$throttler**

**Comment by GrahamCampbell** [comment]
> "graham-campbell/throttle": "~4.0"

That is correct. You are looking at the docs for the upcoming v4 release.

**Comment by GrahamCampbell** [comment]
For 3.0, see https://github.com/GrahamCampbell/Laravel-Throttle/tree/v3.0.0.

**Comment by GrahamCampbell** [comment]
Thanks for the type report. I've fixed that now. :)
