### ISSUE TITLE
Add function to check unlock time?

### ISSUE THREAD

**Issue by JonathanGuo** [GrahamCampbell/Laravel-Throttle#29]
I read through the codes so I know how the logic is meant to be. But in some cases, application may hit() only if check() succeeds.
In my case:
```PHP
$throttler = Throttle::get($request, $maxAttempts, $minsToHold);
try {
    if( $throttler->check() ) {
        //validate data
        if( $validator->fails() ) {
            $throttler->hit();
            //throw new \Exception;
        }
        $throttler->clear();
    } else {
        //throw new \Exception
        //The message needs to tell users how long they need to wait
    }
} catch (\Exception $e) {
...
}
```

I am not sure if it would be good to add following function into CacheThrottler class.
```PHP
class CacheThrottler implements ThrottlerInterface, Countable
{
    //....
    /**
     * Get time the user needs to wait
     * @return int
     */
    public function timeToUnlock()
    {
        $parts = array_slice(str_split($hash = md5($this->key), 2), 0, 2);
        $dir = $this->store->getDirectory();
        $path = $dir.'/'.implode('/', $parts).'/'.$hash;
        $expire = substr($this->store->getFilesystem()->get($path), 0, 10);
        $timeToUnlock = intval(ceil(($expire - time()) / 60));
        return $timeToUnlock;
    }
}
```

I am really not sure if this function should be added. Because according to attempt() function, it refreshes the lock time if users try after frozen.

Shall I make a pull request to add it?

**Comment by GrahamCampbell** [comment]
I think the current implementation is fine.

**Comment by GrahamCampbell** [comment]
The idea is to use the cache driver itself to deal with expiry, not implement something else as well.

**Comment by JonathanGuo** [comment]
@GrahamCampbell Oh yes. I think in my case I probably create my own class.

**Comment by GrahamCampbell** [comment]
Yeh, this package is specifically designed so that you can find yourself a new factory and generate your own class.

**Comment by GrahamCampbell** [comment]
Implement and rebind https://github.com/GrahamCampbell/Laravel-Throttle/blob/master/src/Factories/FactoryInterface.php and you're sorted for returning your own implementation of https://github.com/GrahamCampbell/Laravel-Throttle/blob/master/src/Throttlers/ThrottlerInterface.php.

**Comment by JonathanGuo** [comment]
Cool. Thanks a lot.
