### ISSUE TITLE
Wrong version when use composer update

### ISSUE THREAD

**Issue by jyhsu2000** [GrahamCampbell/Laravel-Throttle#32]
I set the following require in `composer.json`
```
"graham-campbell/throttle": "^4.1",
```
Means version >= 4.1 and <5.0.
When I use `composer update`,
it doesn't use `v4.1.1` by you.
But it uses `v4.3.1` by another author.

I think there is something wrong because there are others' releases on you release page.
I don't know if it's reason or not.
Maybe it would cause to user get wrong version through composer.
And difference in namespace of code would break projects which use this project.
Actually, this is just happened to me.

![screenshot_20150822_234239](https://cloud.githubusercontent.com/assets/6276648/9424710/942553ea-4928-11e5-8049-aa8893902b4e.png)

Use `4.1.*` as version number to specify to your version can prevent this things happens.
But it's not a fundamental solution.
Please fix it.
Thanks.

**Comment by GrahamCampbell** [comment]
Oops. Sorry about that.
