### ISSUE TITLE
Throttle check function always returns true

### ISSUE THREAD

**Issue by r-a-o** [GrahamCampbell/Laravel-Throttle#38]
I have the following in my Route file,

```
use GrahamCampbell\Throttle\Facades\Throttle;
use Illuminate\Support\Facades\Request;

Route::get('throttle-check', function(){
    $throttler = Throttle::get(Request::instance(), 5, 3);
    // let's check if we've gone over the limit
    var_dump($throttler->check());
    // count
    var_dump(count($throttler));
});
```
When I run this, it always returns `bool(true) int(0)` 
Even on the first run.

Am I doing something wrong or is it the package?

I am using the latest version (5.1.0) on Laravel 5.1.24 (LTS)

**Comment by GrahamCampbell** [comment]
That is correct. It returns false when you're over the limit.

**Comment by GrahamCampbell** [comment]
Our tests confirm that this package works fine. Perhapse you're cache driver is wrong? What cache driver are you using?

**Comment by GrahamCampbell** [comment]
NB: Our functional tests: https://github.com/GrahamCampbell/Laravel-Throttle/blob/master/tests/Functional/MiddlewareTest.php.

**Comment by r-a-o** [comment]
In throttle config file, 'driver' is set to `null`. My CACHE_DRIVER is set to "file". 

>That is correct. It returns false when you're over the limit.

No, its says that the limit is already reached even on the first run.

**Comment by r-a-o** [comment]
But the middleware is working fine.
```
Route::get('middleware-throttle-check', ['middleware' => 'throttle:6:1', function () {
    return 'Hello there!';
}]);
```

**Comment by GrahamCampbell** [comment]
Well, the middleware calls the same object under the hood, so it must work correctly?

**Comment by r-a-o** [comment]
Yup, weird. Checked again, something is definitely wrong.

**Comment by r-a-o** [comment]
I didn't call `hit` or `attempt` and was expecting the counter to increment :| 
My bad.

**Comment by GrahamCampbell** [comment]
Glad you got it solved. :)
