### ISSUE TITLE
Throttle based on a JWT token instead of IP address

### ISSUE THREAD

**Issue by rohitnaidu19** [GrahamCampbell/Laravel-Throttle#39]
I am using JWT token in header to authorize users. So I can uniquely identify a particular user with the token. Can I use this JWT token instead of IP address to identify a user. Multiple users behind a Proxy server can cause problems with IP address filtering.
If I can uniquely identify a user i can set exact limits like 3 login attempts/hr. 
How can i do this?

**Comment by GrahamCampbell** [comment]
Already possible. Just a pass through an array instead of a request object.

**Comment by GrahamCampbell** [comment]
https://github.com/GrahamCampbell/Laravel-Throttle/blob/master/src/Throttle.php#L68

**Comment by GrahamCampbell** [comment]
https://github.com/GrahamCampbell/Laravel-Throttle/blob/master/src/Transformers/ArrayTransformer.php

**Comment by GrahamCampbell** [comment]
So, basically, pass through the token as the "ip" in the array you give.

**Comment by GrahamCampbell** [comment]
I'm considering renaming "ip" to "id" or something in a later version.

**Comment by rohitnaidu19** [comment]
Could u gv me an example with authorization header and bearer contains jwt.
I'm using laravel 5 and using tymon/jwt .

Regards,
Rohit Naidu

**Comment by GrahamCampbell** [comment]
Not really. It should be pretty trivial for you to read the header and pass it through?

**Comment by rohitnaidu19** [comment]
Thanks for the links . It helped :-)
