### ISSUE TITLE
Github description

### ISSUE THREAD

**Issue by garygreen** [GrahamCampbell/Laravel-Throttle#40]
> A rate limiter for Laravel 5 https://gjcampbell.co.uk/

It's not only for Laravel 5 but supports older versions too (can be confusing when your viewing the 2.0.2 tag and lower).

**Comment by jbrooksuk** [comment]
I think it's more that older versions aren't supported anymore.

**Comment by garygreen** [comment]
Sure, but when you change to view a certain tag the description stays the same on Github even though the actual version your viewing supports 4.1/4.2, just a minor thing that can be confusing.

**Comment by GrahamCampbell** [comment]
The current description describes what the current version supports.

**Comment by GrahamCampbell** [comment]
I would not recommend still using Laravel 4 for security reasons.
