### ISSUE TITLE
How to install on Laravel 5.0

### ISSUE THREAD

**Issue by zenichanin** [GrahamCampbell/Laravel-Throttle#43]
I added `"graham-campbell/throttle": "^5.0"` to composer but I keep getting various incompatibilities in when composer tries to update.  Is there some other version I should be trying?

Here's the error:

Problem 1
    - illuminate/cache v5.2.25 requires illuminate/contracts 5.3.* -> no matching package found.
    - Conclusion: remove laravel/framework v5.0.35
    - Conclusion: don't install laravel/framework v5.0.35
    - graham-campbell/throttle v5.0.0 requires illuminate/cache 5.1.* -> satisfiable by illuminate/cache[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.6, v5.1.8].
    - graham-campbell/throttle v5.1.0 requires illuminate/cache 5.1.*|5.2.* -> satisfiable by illuminate/cache[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.6, v5.2.7].
    - graham-campbell/throttle v5.1.1 requires illuminate/cache 5.1.*|5.2.* -> satisfiable by illuminate/cache[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.6, v5.2.7].
    - don't install illuminate/cache v5.1.1|don't install laravel/framework v5.0.35
    - don't install illuminate/cache v5.1.13|don't install laravel/framework v5.0.35
    - don't install illuminate/cache v5.1.16|don't install laravel/framework v5.0.35
    - don't install illuminate/cache v5.1.2|don't install laravel/framework v5.0.35
    - don't install illuminate/cache v5.1.20|don't install laravel/framework v5.0.35
    - don't install illuminate/cache v5.1.22|don't install laravel/framework v5.0.35
    - don't install illuminate/cache v5.1.25|don't install laravel/framework v5.0.35
    - don't install illuminate/cache v5.1.28|don't install laravel/framework v5.0.35
    - don't install illuminate/cache v5.1.30|don't install laravel/framework v5.0.35
    - don't install illuminate/cache v5.1.31|don't install laravel/framework v5.0.35
    - don't install illuminate/cache v5.1.6|don't install laravel/framework v5.0.35
    - don't install illuminate/cache v5.1.8|don't install laravel/framework v5.0.35
    - don't install illuminate/cache v5.2.0|don't install laravel/framework v5.0.35
    - don't install illuminate/cache v5.2.19|don't install laravel/framework v5.0.35
    - don't install illuminate/cache v5.2.21|don't install laravel/framework v5.0.35
    - don't install illuminate/cache v5.2.24|don't install laravel/framework v5.0.35
    - don't install illuminate/cache v5.2.26|don't install laravel/framework v5.0.35
    - don't install illuminate/cache v5.2.6|don't install laravel/framework v5.0.35
    - don't install illuminate/cache v5.2.7|don't install laravel/framework v5.0.35
    - Installation request for laravel/framework == 5.0.35.0 -> satisfiable by laravel/framework[v5.0.35].
    - Installation request for graham-campbell/throttle ~5.0 -> satisfiable by graham-campbell/throttle[v5.0.0, v5.1.0, v5.1.1].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

**Comment by GrahamCampbell** [comment]
We only support 5.1 and upwards.

**Comment by GrahamCampbell** [comment]
Version 3.x of this package was the last to support laravel 5.0. You can install that if you want.

**Comment by zenichanin** [comment]
Thanks I'll try version 3.x

**Comment by GrahamCampbell** [comment]
The docs for that version are here btw: https://github.com/GrahamCampbell/Laravel-Throttle/tree/v3.0.0.
