### ISSUE TITLE
Response Message

### ISSUE THREAD

**Issue by mehdibahraami** [GrahamCampbell/Laravel-Throttle#44]
Hi,
I want to give this message to user:
```
response()->json([
	        'message' => 'Too Many Attempts',
	        'code' => 429
        ], 429);
```
But Throttle message is in your ThrottleRequests.
Please add a new input parameter for response message.

**Comment by GrahamCampbell** [comment]
Just catch the exception in your exception handler, and handle it properly there.

**Comment by mehdibahraami** [comment]
I added this in exception handler but it show me again "Too Many Attempts."
```
public function render($request, Exception $e)
	{
		if($e instanceof TooManyRequestsHttpException) {
			return response()->json([
				'message' => 'Too Many Attempts',
				'code' => 429
			], 429);
		}

		return parent::render($request, $e);
	}
```

**Comment by floringavrila** [comment]
use Symfony\Component\HttpKernel\Exception\HttpException;
...
     if($exception instanceof HttpException && $exception->getStatusCode() == 429) {
            return response()->json([
                'message' => 'Too Many Attempts',
                'code' => 429
            ], 429)->withHeaders($exception->getHeaders());
                                       
        }
