### ISSUE TITLE
Middleware not clearing counts?

### ISSUE THREAD

**Issue by oceanwap** [GrahamCampbell/Laravel-Throttle#46]
1. I am using the middleware but once limit is reached it's not clearing counts. 
2. How to get retry-after time and remaining request counts?

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch.

1. Yeh, it'll only clear it once the time needed has passed.
2. There is no way to do this. Perhaps
 check out my other package: https://github.com/AltThree/Throttle.

**Comment by oceanwap** [comment]
1. I mean, It's not clearing after specified amount of time passed. Like I added middleware ['throttle:30,1'] so it should clear it after one minute but it's not.

2. Thanks, but alt-three supports only 5.2+, If I were using 5.2 then wouldn't have needed any package as 5.2 has the built-in throttle.

**Comment by GrahamCampbell** [comment]
If you hit it again during that minute, it resets the count down so you have to wait another minute I think. Honestly, I actually can't remember off the top of my head. It was a while since I wrote this.

> If I were using 5.2 then wouldn't have needed any package as 5.2 has the built-in throttle.

That alt three package uses the built in throttler, but provides a better middleware than what's in the core.

**Comment by oceanwap** [comment]
I left it for more than 10 minutes(approx) but still no clue when will it allow me. As 5.1 is an LTS version so don't want to switch to 5.2 till 6.1 is released.

Can I do a pull request?

**Comment by GrahamCampbell** [comment]
It doesn't need to call clear anywhere. The cache should expire automatically. What cache driver are you using?

**Comment by oceanwap** [comment]
Earlier I was using "redis", I thought this might be the issue then I tried with "file", but still no luck.

**Comment by GrahamCampbell** [comment]
Hmm, well, I'm not sure if this is a bug here if cache expiration isn't working.

**Comment by oceanwap** [comment]
Ok, I will see what to do.

**Comment by oceanwap** [comment]
At least package should be there for 5.1 LTS, You might have seen it just that in Laravel 5.2 there are 2 cached params.

You can make it like that or I can make a pull request. That way it can have remaining hit count, retry after time like things which you added in alt-three.

**Comment by GrahamCampbell** [comment]
> 6.1 is released.

There's no reason to assume that that will be an LTS release. Infact, there's no reason to assume there actually will be another LTS laravel release at this point.

**Comment by oceanwap** [comment]
No problem. I created a package taking some of your code and some from 5.2
and it's working just awesome in 5.1 along with nginx rate limits.
If you allow I will create a pull request to update package so others who
are using 5.1, can benefit from it. Everyone can't upgrade too quickly, as
it may generate issues in live site, unless full tested and that takes time.

**Comment by coolynx** [comment]
Is this fixed?

I'm using memcached Cache driver and it does not automatically clear cache limit. It continues to increase the negative time remaining.

```
16:31:30.436 Server: nginx/1.11.5
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
X-Powered-By: PHP/7.0.11
Cache-Control: no-cache
X-RateLimit-Limit: 60
X-RateLimit-Remaining: 0
Retry-After: -1345
X-RateLimit-Reset: 1478354945
phpdebugbar-id: f767cd4383b12bf7a043e2261197d9ba
Date: Sat, 05 Nov 2016 14:31:30 GMT
```
