### ISSUE TITLE
Wrong documentation for check() method

### ISSUE THREAD

**Issue by dave7280** [GrahamCampbell/Laravel-Throttle#50]
> The 'check' method will return a boolean representing whether or not the hit limit has been exceeded.

It seems that it will return false when limit has been hit? 

```
  public function check()
    {
        return $this->count() < $this->limit;
    }

```

```
Assume hit count is = $this->count() =  50
Limit is = $this->limit =  10

return 50 < 10

check() = 50 < 10 = false

```

**Comment by GrahamCampbell** [comment]
Badly worded. It returns true while the limit is not exceeded.

**Comment by GrahamCampbell** [comment]
I mean, the documentation, strictly, is not wrong. It does return a boolean representing those two states.
