### ISSUE TITLE
not working for me

### ISSUE THREAD

**Issue by charanjeet5ingh** [GrahamCampbell/Laravel-Throttle#51]
i am using this code

```
use GrahamCampbell\Throttle\Facades\Throttle;
use Illuminate\Support\Facades\Request;

$throttler = Throttle::get(Request::instance(), 10, 1);

// let's check if we've gone over the limit
        var_dump($throttler->check());

// we implement Countable
        var_dump(count($throttler));
```

but i am not getting count and true or false for check() method. and also i am using cache with file

**Comment by GrahamCampbell** [comment]
How do you mean?

**Comment by charanjeet5ingh** [comment]
Its not increasing count number and i am not able to throttle the link

**Comment by GrahamCampbell** [comment]
That example will not increment the count. You must call `hit` to increment the count by one, or call `attempt`, which calls `hit`, then calls `check` and returns the result.

**Comment by GrahamCampbell** [comment]
See the example middleware shipped with this package: https://github.com/GrahamCampbell/Laravel-Throttle/blob/master/src/Http/Middleware/ThrottleMiddleware.php#L56-L63.

**Comment by charanjeet5ingh** [comment]
okay got it thanks

**Comment by charanjeet5ingh** [comment]
sorry but i used 
` var_dump(Throttle::attempt($request),2,1);`

but after getting false for check i am not able to get true for check

**Comment by GrahamCampbell** [comment]
You're passing 2 and 1 as parameters to var_dump, not to attempt.
