### ISSUE TITLE
Method to get next "reset" timestamp

### ISSUE THREAD

**Issue by Andreyco** [GrahamCampbell/Laravel-Throttle#55]
Add method, which lets you know when counter is reset.  
Useful as part of response payload (or headers) to client's requests.

**Comment by GrahamCampbell** [comment]
Not in this package, but if you're using a newish laravel version, I'd recommend https://github.com/AltThree/Throttle. Kinda a successor to this package, but not quite the same.

**Comment by Andreyco** [comment]
Nope, still on 5.2, not planing to update tho...
Looking at `AltThree/Throttle`, it's middleware... It runs before requests are self validated, correct? 
I need to rate limit request that contain valid data (do not throw 422).

**Comment by GrahamCampbell** [comment]
> Nope, still on 5.2

That's ok then. 5.2 is supported there, but 4.1 is not.

>Looking at AltThree/Throttle, it's middleware... It runs before requests are self validated, correct?

No, you can insert the middleware in the pipeline whereever you want. You also don't have to use the middleware directly. If that's the case, then I'd recommend using Laravel's native throttling facilities.
