### ISSUE TITLE
Can i throttle on the bases of ip address and one unique key

### ISSUE THREAD

**Issue by charanjeet5ingh** [GrahamCampbell/Laravel-Throttle#56]
I am developing an application where the request will come from only one place and i want to throttle it on the bases of single ip address or hash key

**Comment by GrahamCampbell** [comment]
Short answer is yes. You basically need to implement your own transformer, and bind that to the ioc.

**Comment by GrahamCampbell** [comment]
https://github.com/GrahamCampbell/Laravel-Throttle/tree/master/src/Transformers

**Comment by GrahamCampbell** [comment]
https://github.com/GrahamCampbell/Laravel-Throttle/blob/master/src/ThrottleServiceProvider.php#L86-L98
