### ISSUE TITLE
Race condition with hit()

### ISSUE THREAD

**Issue by Sly-Ripper** [GrahamCampbell/Laravel-Throttle#57]
If you create a Throttle and the cache expires before you hit(), the key will be stored with -1 ttl (in Redis at least).

I would guess if [this](https://github.com/GrahamCampbell/Laravel-Throttle/blob/master/src/Throttlers/CacheThrottler.php#L130-L132) was removed, the cache would be checked instead of relying on the Throttle's own variable leading to no expiration.

**Comment by GrahamCampbell** [comment]
I think keeping our own internal variable is fine, since throttling is fine to be approximate. If it needs to be sequential, then you could use a locking package to prevent multiple parallel requests per user.

I do need to fix the -1 ttl issue though. Could you PR that please?

**Comment by jitendra-1217** [comment]
@GrahamCampbell Facing this same issue and I understand a lot of people would too.

I wanted to PR this but confused on following:

The simplest fix was:

```diff
diff --git a/src/Throttlers/CacheThrottler.php b/src/Throttlers/CacheThrottler.php
index 1c3743b..8921bf5 100644
--- a/src/Throttlers/CacheThrottler.php
+++ b/src/Throttlers/CacheThrottler.php
@@ -98,6 +98,7 @@ class CacheThrottler implements ThrottlerInterface, Countable
     public function hit()
     {
         if ($this->count()) {
+            $this->store->add($this->key, 0, $this->time);
             $this->store->increment($this->key);
             $this->number++;
         } else {
```

- This increase number of redis calls by 1 every api requests
- Also add() is not enformed in Illuminate\Contracts\Cache, available in redis, memcached though.

---

To avoid multiple redis call (for people using redis) can we conditionally(if store is redis, will change below diff) call lua script like below:

```diff
diff --git a/src/Throttlers/CacheThrottler.php b/src/Throttlers/CacheThrottler.php
index 1c3743b..68b27a2 100644
--- a/src/Throttlers/CacheThrottler.php
+++ b/src/Throttlers/CacheThrottler.php
@@ -97,13 +97,11 @@ class CacheThrottler implements ThrottlerInterface, Countable
      */
     public function hit()
     {
-        if ($this->count()) {
-            $this->store->increment($this->key);
-            $this->number++;
-        } else {
-            $this->store->put($this->key, 1, $this->time);
-            $this->number = 1;
-        }
+        $lua = 'local v = redis.call('incr', KEYS[1]) ' .
+               'if v>1 then return v ' .
+               'else redis.call('setex', KEYS[1], ARGV[1], 1) return 1 end';
+
+        $this->number = $this->store->connection()->eval($lua, 1, $this->key, $this->time);

         return $this;
     }
```

---

Awaiting your suggestion on this please.

**Comment by jitendra-1217** [comment]
@Sly-Ripper : Did you have any luck(how?) fixing this in your use?
