### ISSUE TITLE
Is it possible to turn rate limit down for a specific origin?

### ISSUE THREAD

**Issue by romulo-rocha** [GrahamCampbell/Laravel-Throttle#62]
This is not exactly an issue, but I think it'd be interesting to have this question documented in this package.

I have a Laravel-made API running in a server and an Angular application running in another server. My Angular app loads a huge JSON file (with more than 500 lines) and tries to insert each line in a database through the api. A request is sent for each line, so I get a 409 error (too many requests).

I know this is a matter of security, so I don't want to remove the throttle from my middlewareGroup array in Kernel.php. I'd like to know, however, if there's any chance I can turn this rate limit down for a specific origin address (http://www.myangularapp.com/ only, for example)? So I can send these various requests while keeping the rate limit for other origin addresses.

Thanks in advance!

**Comment by GrahamCampbell** [comment]
Yes, you can write your own middleware.
