### ISSUE TITLE
Not working with memcached

### ISSUE THREAD

**Issue by gcphost** [GrahamCampbell/Laravel-Throttle#66]
Tested on homestead and a staging server @ amazon. Both fail to work when cache driver is memcached. Works fine for redis and file drivers.

```
CACHE_DRIVER=memcached
```

```
dd(Throttle::attempt([
  'ip' => request()->ip(),
], 2, 60));
```
Always returns true.

Switch drivers around, after 2 calls, returns false.

We've switched to redis due to high volume issues related to amazons memcached servers so the issue is null for us now, just wanted to bring it to your attention.

Thanks for all your work Graham!

**Comment by GrahamCampbell** [comment]
Thanks for the report. 👍

**Comment by GrahamCampbell** [comment]
I think I'll have to call this a no-fix. Redis is definitely the best choice here, and I've just merged in a PR that makes Redis support even better. I'll be releasing V7.0 shortly. :)
