### ISSUE TITLE
About php version

### ISSUE THREAD

**Issue by saifuldhaka** [GrahamCampbell/Laravel-Throttle#71]
HI,
in your documentation, you mentioned Laravel Throttle requires PHP 7. But when i tried to install it, i got this error.
`
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - doctrine/instantiator 1.1.0 requires php ^7.1 -> your PHP version (7.0.22) does not satisfy that requirement.
    - doctrine/instantiator 1.1.0 requires php ^7.1 -> your PHP version (7.0.22) does not satisfy that requirement.
    - Installation request for doctrine/instantiator (locked at 1.1.0) -> satisfiable by doctrine/instantiator[1.1.0].

Installation failed, reverting ./composer.json to its original content.
`

I am using laravel 5.4

Thanks

**Comment by GrahamCampbell** [comment]
We don't require doctrine instantiator. Please run `composer why doctrine/instantiator`.

**Comment by saifuldhaka** [comment]
Thanks, i solve that issue,
But one more thing i need suggestion from you.
i am trying to use in my custom login application, but facing issue with 
`use Illuminate\Http\Request;
use Illuminate\Support\Facades\Request;
`
cant use both in same time. when using 
`use Illuminate\Http\Request;`   following code block works fine 
`$data = array(
          'email' => $request->input('email'),
          'password' => $request->input('password'),
          'status' => 1
      );
` but `
$throttler = Throttle::count(Request::instance(), 5, 1);
      echo $throttler;` not works. The opposite happens when use use Illuminate\Support\Facades\Request;  
, input showing errors.

here is the errors both 
`FatalThrowableError
Type error: Argument 1 passed to App\Http\Controllers\Controller::validate() must be an instance of Illuminate\Http\Request, `
and 
`ErrorException
Non-static method Illuminate\Http\Request::instance() should not be called statically`

thanks

**Comment by GrahamCampbell** [comment]
You need `Illuminate\Support\Facades\Request`.

**Comment by saifuldhaka** [comment]
thanks, i solved it by route.
`
Route::group(['middleware'=>'throttle:2,10'], function(){
  Route::post('/login', 'LoginController@login')->name("login");
});
`
and update the kernel as: 
`
'throttle' => \App\Http\Middleware\ThrottleRequests::class,
`
thanks for your great efforts
