### ISSUE TITLE
Q: Is it possible that using this middleware triggers Too many redirects?

### ISSUE THREAD

**Issue by thomasmoors** [GrahamCampbell/Laravel-Throttle#73]
As per title, but with some more info.

We got a website with many visitors. For some reason this week we get a Too Many Redirects error in chrome sometimes, the same week we turned on Throttle middleware for web. We are on Laravel 5.5.

Is there any reason to suspect this middleware is the cause for this problem?

**Comment by GrahamCampbell** [comment]
Don't think so, sorry. You can see this from the code too: https://github.com/GrahamCampbell/Laravel-Throttle/blob/master/src/Http/Middleware/ThrottleMiddleware.php. There's no magic going on, just what's there. :)

**Comment by thomasmoors** [comment]
Thanks for the response and yes I did look at the code, however I needed to be 100% sure. Have a nice weekend!

**Comment by GrahamCampbell** [comment]
No problem. 👍
