### ISSUE TITLE
Can we use throttle per day?

### ISSUE THREAD

**Issue by aminraeisi** [GrahamCampbell/Laravel-Throttle#84]
First of all thanks for this great package :+1: 

Is it possible to  have limit for every day instead of every minutes.
In the examples you have this:

```
Route::get('foo', ['middleware' => 'GrahamCampbell\Throttle\Http\Middleware\ThrottleMiddleware:50,30', function () {
    return 'Why herro there!';
}]);
```

Which has limit of 50 hits per minutes (if I am not mistaken) with retention time of 30 minutes.

I have a route that sends OTP through sms and I want to limit that so that only 3 per day/per user(or IP) gets sent. Is there a way to do it with this package? or my case does not require this?

**Comment by GrahamCampbell** [comment]
Yeh, just use the number of minutes in a day. :)

**Comment by GrahamCampbell** [comment]
If you need per actual day, than per 24 hour period starting from the first fresh request made, then you will need to write your own code to do this, since this package is not designed to do this.

**Comment by GrahamCampbell** [comment]
Just use the number of minutes in 24 hours as the number, instead of 30.
