### ISSUE TITLE
multiple throttlers

### ISSUE THREAD

**Issue by edgreenberg** [GrahamCampbell/Laravel-Throttle#86]
I would like to have a piece of middleware that works with multiple throttlers, each with it's own maxAttempts and decayMinutes.

For example:
bad api token submitted (3,60)
per ip address hit counter (100,1)
per api token hit counter (100,1)

I am not sure how to specify something that will get me these throttler objects each time the middleware runs.  Do I need to subclass ThrottleRequest for each one? That seems doable, but wanted to check that I wasn't missing anything simpler. 

Many thanks, 
Ed Greenberg

**Comment by edgreenberg** [comment]
Disregard

**Comment by efroim102** [comment]
@edgreenberg How did you resolve this? by passing a dynamic/custom parameter as the key?

**Comment by edgreenberg** [comment]
@efroim102  Hi Efroim, So I figured out I was asking the wrong question. I didn't need to subclass the throttlers since each one is based on a singleton (deep down inside.)     All I need to do is use a unique route for each one.  

So....
```
        $ip_throttle = Throttle::get($request, API_IP_COUNTER_MAX+1, API_IP_COUNTER_CLEAR_MINUTES);
        $ip_throttle->hit();
        if($ip_throttle->check() === false){
            $response = $next($request);
            $response->header('X-IP-Throttle-Fail', $ip_throttle->count());
            $response->header('X-IP-Throttle-Setting', API_IP_COUNTER_MAX+1);
            $response->header('X-IP-Throttle-Time-Limit', API_IP_COUNTER_CLEAR_MINUTES);
            
            return $response->setContent(json_encode(['error'=>'Too many requests for IP address']));
        }
```
Note that this is not a real route, but that doesn't matter. It's a string. That's all that seems to count.

But what if you want to throttle on something other than an IP address. For instance a user_id.  In my case, a bearer token:

```
        // get the bearer token for use as an "ip address"
        $auth = $request->header('authorization');
        $key_throttle = Throttle::get(
            [
                'ip'    => $auth,
                'route' => 'key_throttle',
            ], API_KEY_COUNTER_MAX+1, API_KEY_COUNTER_CLEAR_MINUTES);
        $key_throttle->hit();
        if($key_throttle->check() === false){
            $response = $next($request);
            $response->header('X-Token-Throttle-Fail', $key_throttle->count());
            $response->header('X-Token-Throttle-Setting', API_KEY_COUNTER_MAX);
            $response->header('X-Token-Throttle-Time-Limit', API_KEY_COUNTER_CLEAR_MINUTES);
            return $response->setContent(json_encode(['error'=>'Too many requests for bearer token']));
        }
```

So the thing that wasn't obvious is that neither the ip nor route needs to be an actual ip or a route. 

Hope this helps. 
Ed Greenberg
Glens Falls, NY

PS: Chag Chanukah Sameach

**Comment by efroim102** [comment]
@edgreenberg Thanks for the prompt response and Chag Chanukah Sameach to you too.

My use case is to throttle requests at the controller level, I have a user registration endpoint which I want to throttle dynamically based on input validation errors.

For ex: if a client requests to register multiple times with different already-claimed email addresses I want the throttle rate limiting config to be different then when the attempt to register multiple times with different already-claimed usernames.

In this case it's to discourage spamming registration to discover active usernames & email-addresses.
