### ISSUE TITLE
Question: Compared to Laravel 5.7

### ISSUE THREAD

**Issue by robov** [GrahamCampbell/Laravel-Throttle#87]
By reading your documentation I could not get the advantages of using your packaged, compared to the built in throttle of laravel 5.7. Am I missing something ?

**Comment by GrahamCampbell** [comment]
This package was written before Laravel had a trottle in it's core, and is maintained so that people don't have to change their existing code. For new apps, probably just use Laravel's built in throttler.

**Comment by robov** [comment]
Thanks... I am new to laravel so I am getting  used to the ecosystem

**Comment by GrahamCampbell** [comment]
No problem. :)
