### ISSUE TITLE
Rate limit for N doesn't work.

### ISSUE THREAD

**Issue by ssi-anik** [GrahamCampbell/Laravel-Throttle#88]
If I try to limit API calls by putting 5, attempt method returns false when the count reaches to 7. So, the user is still getting N+1 requests within that time variable.

[https://github.com/GrahamCampbell/Laravel-Throttle/blob/260693711d203d8a75d36b8d49d58d1e82341dc3/src/Throttlers/CacheThrottler.php#L142](https://github.com/GrahamCampbell/Laravel-Throttle/blob/260693711d203d8a75d36b8d49d58d1e82341dc3/src/Throttlers/CacheThrottler.php#L142)

**Comment by GrahamCampbell** [comment]
The tests indicate this is not the case: https://github.com/GrahamCampbell/Laravel-Throttle/blob/master/tests/Functional/MiddlewareTest.php. 5 hits is allowed, but 6 fails.

**Comment by ssi-anik** [comment]
Custom limit set to 5, you hit 6 times programmatically and manually hitting 7th time shows you an error. Not sure if that's what it is doing or not in my basic understanding in your test case.

But, setting limit to 5, `attempt` should return true for (6 <= 5+1) IMO. please check.

**Comment by GrahamCampbell** [comment]
Hmm, it seems I added the `+ 1` following https://github.com/GrahamCampbell/Laravel-Throttle/issues/6.

**Comment by ssi-anik** [comment]
So, is this a bug or something?
