### ISSUE TITLE
Can I exponentially block a users that triggers the throttle consecutively?

### ISSUE THREAD

**Issue by Gicminos** [GrahamCampbell/Laravel-Throttle#95]
Dear all,

Is it possible to make the throttle exponential?

Let me explain better:

1. A user is initally blocked for 1 minute
2. If The user reaches the limit again in the 1 minute after, he is then blocked for 2 minutes
3. If all this happens again, the user is blocked for 4 minutes
4. If the user behave well in the next 4 minutes, the block gets reduced to 2 and so on

Is it something this package allows or easy to implement? Thank you for your time

**Comment by GrahamCampbell** [comment]
I think that logic would require you to implement your own https://github.com/GrahamCampbell/Laravel-Throttle/blob/8.0/src/Throttler/ThrottlerInterface.php which does that behaviour. You can then plug it into the package.
