### ISSUE TITLE
Attention when using symphony getClientIp

### ISSUE THREAD

**Issue by a21ns1g4ts** [GrahamCampbell/Laravel-Throttle#96]
In some cases a request passes through a proxy, certain request information is sent using either the standard Forwarded header or X-Forwarded-* headers. For example, instead of reading the REMOTE_ADDR header (which will now be the IP address of your reverse proxy), the user's true IP will be stored in a standard Forwarded: for="..." header or a X-Forwarded-For header.  If you don't configure Symfony to look for these headers, you'll get incorrect information about the client's IP address, whether or not the client is connecting via HTTPS, the client's port and the hostname being requested.
https://symfony.com/doc/current/deployment/proxies.html

**Comment by GrahamCampbell** [comment]
Yes, this is correct. Laravel out of the box ships with a middleware for this. You need to add your proxies to it (by reading from config or otherwise): https://github.com/laravel/laravel/blob/master/app/Http/Middleware/TrustProxies.php#L15.

**Comment by a21ns1g4ts** [comment]
Yep, but I use lumen. `Fideloper\Proxy\TrustProxies` is not a dependence. Any way i have set `['127.0.0.1', 'REMOTE_ADDR']` in `\Illuminate\Http\Request\Request::setTrustedProxies`.
