### ISSUE TITLE
Issue with Memcached

### ISSUE THREAD

**Issue by AmitLekhi1990** [GrahamCampbell/Laravel-Throttle#98]
@GrahamCampbell I suppose you already know as I saw your comment on one of the issue that this package is not working if cache driver used is `Memcached`. I am getting the similar issue where `attempt()` always return `true` and `count` stops getting increment after 2.

Similar issue - https://github.com/GrahamCampbell/Laravel-Throttle/issues/66

If there is no fix, can you please add this in doc?

**Comment by GrahamCampbell** [comment]
What version of the package are you using?

**Comment by AmitLekhi1990** [comment]
I am using v6.0 as our project is on Laravel 5.3

**Comment by GrahamCampbell** [comment]
Sorry, only the latest version is supported. Please upgrade to Laravel 6 LTS as soon as possible, and open a new issue if this persists on the latest version.
