### ISSUE TITLE
Compatible with Countable::count() error

### ISSUE THREAD

**Issue by jonhassall** [GrahamCampbell/Laravel-Throttle#99]
**PHP version**: 8.1.1

**Description**
I am getting the following error when using the latest version of Laravel-Throttle with the latest version of Laravel:

PHP message: PHP Deprecated:  Return type of GrahamCampbell\Throttle\Throttler\CacheThrottler::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in .../vendor/graham-campbell/throttle/src/Throttler/CacheThrottler.php on line 135" while reading response header from upstream

Happy to try any suggestions.

**Comment by jonhassall** [comment]
Was a dependency issue, fixed.

**Comment by GrahamCampbell** [comment]
Thanks for the report.

**Comment by GrahamCampbell** [comment]
Fixed in v8.2.0. :)
